    FROM php:7.0-fpm  
    # RUN docker-php-ext-install pdo_mysql 
    RUN mkdir -p /var/www/html/pictures
    RUN chmod 777 /var/www/html/pictures
    RUN chown -R www-data:www-data /var/www/html/pictures
    # RUN mkdir -p /var/www/html/mapMaterials
    # RUN chmod 777 /var/www/html/mapMaterials
    # RUN chown -R www-data:www-data /var/www/html/mapMaterials